FROM python:3.6-alpine

RUN apk update && apk add python3-dev build-base git

WORKDIR /app
COPY setup.py .
COPY xain_fl xain_fl/
COPY README.md .

RUN pip install -v -e .

CMD ["python3", "setup.py", "--fullname"]
