# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xain/network/network.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='xain/network/network.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1axain/network/network.proto\"F\n\rClientMessage\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\r\n\x03\x66oo\x18\x02 \x01(\x02H\x00\x12\r\n\x03\x62\x61r\x18\x03 \x01(\x02H\x00\x42\t\n\x07message\"\x81\x01\n\rServerMessage\x12\r\n\x03\x66or\x18\x01 \x01(\x05H\x00\x12+\n\x03\x62\x61r\x18\x02 \x01(\x0b\x32\x1c.ServerMessage.NestedMessageH\x00\x1a)\n\rNestedMessage\x12\x0b\n\x03\x66oo\x18\x01 \x01(\x05\x12\x0b\n\x03\x62\x61r\x18\x02 \x01(\x05\x42\t\n\x07message2F\n\x13\x42idirectionalStream\x12/\n\x07\x43onnect\x12\x0e.ClientMessage\x1a\x0e.ServerMessage\"\x00(\x01\x30\x01\x62\x06proto3')
)




_CLIENTMESSAGE = _descriptor.Descriptor(
  name='ClientMessage',
  full_name='ClientMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='ClientMessage.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='foo', full_name='ClientMessage.foo', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bar', full_name='ClientMessage.bar', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='message', full_name='ClientMessage.message',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=30,
  serialized_end=100,
)


_SERVERMESSAGE_NESTEDMESSAGE = _descriptor.Descriptor(
  name='NestedMessage',
  full_name='ServerMessage.NestedMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='foo', full_name='ServerMessage.NestedMessage.foo', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bar', full_name='ServerMessage.NestedMessage.bar', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=221,
)

_SERVERMESSAGE = _descriptor.Descriptor(
  name='ServerMessage',
  full_name='ServerMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='for', full_name='ServerMessage.for', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bar', full_name='ServerMessage.bar', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SERVERMESSAGE_NESTEDMESSAGE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='message', full_name='ServerMessage.message',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=103,
  serialized_end=232,
)

_CLIENTMESSAGE.oneofs_by_name['message'].fields.append(
  _CLIENTMESSAGE.fields_by_name['foo'])
_CLIENTMESSAGE.fields_by_name['foo'].containing_oneof = _CLIENTMESSAGE.oneofs_by_name['message']
_CLIENTMESSAGE.oneofs_by_name['message'].fields.append(
  _CLIENTMESSAGE.fields_by_name['bar'])
_CLIENTMESSAGE.fields_by_name['bar'].containing_oneof = _CLIENTMESSAGE.oneofs_by_name['message']
_SERVERMESSAGE_NESTEDMESSAGE.containing_type = _SERVERMESSAGE
_SERVERMESSAGE.fields_by_name['bar'].message_type = _SERVERMESSAGE_NESTEDMESSAGE
_SERVERMESSAGE.oneofs_by_name['message'].fields.append(
  _SERVERMESSAGE.fields_by_name['for'])
_SERVERMESSAGE.fields_by_name['for'].containing_oneof = _SERVERMESSAGE.oneofs_by_name['message']
_SERVERMESSAGE.oneofs_by_name['message'].fields.append(
  _SERVERMESSAGE.fields_by_name['bar'])
_SERVERMESSAGE.fields_by_name['bar'].containing_oneof = _SERVERMESSAGE.oneofs_by_name['message']
DESCRIPTOR.message_types_by_name['ClientMessage'] = _CLIENTMESSAGE
DESCRIPTOR.message_types_by_name['ServerMessage'] = _SERVERMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClientMessage = _reflection.GeneratedProtocolMessageType('ClientMessage', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTMESSAGE,
  '__module__' : 'xain.network.network_pb2'
  # @@protoc_insertion_point(class_scope:ClientMessage)
  })
_sym_db.RegisterMessage(ClientMessage)

ServerMessage = _reflection.GeneratedProtocolMessageType('ServerMessage', (_message.Message,), {

  'NestedMessage' : _reflection.GeneratedProtocolMessageType('NestedMessage', (_message.Message,), {
    'DESCRIPTOR' : _SERVERMESSAGE_NESTEDMESSAGE,
    '__module__' : 'xain.network.network_pb2'
    # @@protoc_insertion_point(class_scope:ServerMessage.NestedMessage)
    })
  ,
  'DESCRIPTOR' : _SERVERMESSAGE,
  '__module__' : 'xain.network.network_pb2'
  # @@protoc_insertion_point(class_scope:ServerMessage)
  })
_sym_db.RegisterMessage(ServerMessage)
_sym_db.RegisterMessage(ServerMessage.NestedMessage)



_BIDIRECTIONALSTREAM = _descriptor.ServiceDescriptor(
  name='BidirectionalStream',
  full_name='BidirectionalStream',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=234,
  serialized_end=304,
  methods=[
  _descriptor.MethodDescriptor(
    name='Connect',
    full_name='BidirectionalStream.Connect',
    index=0,
    containing_service=None,
    input_type=_CLIENTMESSAGE,
    output_type=_SERVERMESSAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BIDIRECTIONALSTREAM)

DESCRIPTOR.services_by_name['BidirectionalStream'] = _BIDIRECTIONALSTREAM

# @@protoc_insertion_point(module_scope)
