# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from xain.network import stream_pb2 as xain_dot_network_dot_stream__pb2


class CoordinatorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Train = channel.stream_stream(
        '/Coordinator/Train',
        request_serializer=xain_dot_network_dot_stream__pb2.ParticipantMessage.SerializeToString,
        response_deserializer=xain_dot_network_dot_stream__pb2.CoordinatorMessage.FromString,
        )


class CoordinatorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Train(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CoordinatorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Train': grpc.stream_stream_rpc_method_handler(
          servicer.Train,
          request_deserializer=xain_dot_network_dot_stream__pb2.ParticipantMessage.FromString,
          response_serializer=xain_dot_network_dot_stream__pb2.CoordinatorMessage.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Coordinator', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
