# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from numproto.protobuf.ndarray_pb2 import (
    NDArray as numproto___protobuf___ndarray_pb2___NDArray,
)

from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


class ParticipantMessage(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    uuid = ... # type: typing___Text
    progress = ... # type: float

    def __init__(self,
        *,
        uuid : typing___Optional[typing___Text] = None,
        progress : typing___Optional[float] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> ParticipantMessage: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"progress",u"uuid"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"progress",b"progress",u"uuid",b"uuid"]) -> None: ...

class CoordinatorMessage(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class TrainConfig(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        epochs = ... # type: int
        epoch_base = ... # type: int

        @property
        def theta(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[numproto___protobuf___ndarray_pb2___NDArray]: ...

        def __init__(self,
            *,
            theta : typing___Optional[typing___Iterable[numproto___protobuf___ndarray_pb2___NDArray]] = None,
            epochs : typing___Optional[int] = None,
            epoch_base : typing___Optional[int] = None,
            ) -> None: ...
        @classmethod
        def FromString(cls, s: bytes) -> CoordinatorMessage.TrainConfig: ...
        def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
        def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
        if sys.version_info >= (3,):
            def ClearField(self, field_name: typing_extensions___Literal[u"epoch_base",u"epochs",u"theta"]) -> None: ...
        else:
            def ClearField(self, field_name: typing_extensions___Literal[u"epoch_base",b"epoch_base",u"epochs",b"epochs",u"theta",b"theta"]) -> None: ...

    reconnect_in = ... # type: int

    @property
    def train_config(self) -> CoordinatorMessage.TrainConfig: ...

    def __init__(self,
        *,
        reconnect_in : typing___Optional[int] = None,
        train_config : typing___Optional[CoordinatorMessage.TrainConfig] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> CoordinatorMessage: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"message",u"reconnect_in",u"train_config"]) -> bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"message",u"reconnect_in",u"train_config"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"message",b"message",u"reconnect_in",b"reconnect_in",u"train_config",b"train_config"]) -> bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"message",b"message",u"reconnect_in",b"reconnect_in",u"train_config",b"train_config"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions___Literal[u"message",b"message"]) -> typing_extensions___Literal["reconnect_in","train_config"]: ...
