# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xain/network/stream.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from numproto.protobuf import ndarray_pb2 as numproto_dot_protobuf_dot_ndarray__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='xain/network/stream.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x19xain/network/stream.proto\x1a\x1fnumproto/protobuf/ndarray.proto\"\xab\x01\n\x12ParticipantMessage\x12\x31\n\x06result\x18\x01 \x01(\x0b\x32\x1f.ParticipantMessage.TrainResultH\x00\x12\x1d\n\x12unkown_instruction\x18\xe8\x07 \x01(\x08H\x00\x1a\x38\n\x0bTrainResult\x12)\n\x05theta\x18\x01 \x03(\x0b\x32\x1a.numproto.protobuf.NDArrayB\t\n\x07request\"\xae\x01\n\x12\x43oordinatorMessage\x12\x16\n\x0creconnect_in\x18\x01 \x01(\x05H\x00\x12\x37\n\x0ctrain_config\x18\x02 \x01(\x0b\x32\x1f.CoordinatorMessage.TrainConfigH\x00\x1a\x38\n\x0bTrainConfig\x12)\n\x05theta\x18\x01 \x03(\x0b\x32\x1a.numproto.protobuf.NDArrayB\r\n\x0binstruction2O\n\x12ParticipantManager\x12\x39\n\x07\x43onnect\x12\x13.ParticipantMessage\x1a\x13.CoordinatorMessage\"\x00(\x01\x30\x01\x62\x06proto3')
  ,
  dependencies=[numproto_dot_protobuf_dot_ndarray__pb2.DESCRIPTOR,])




_PARTICIPANTMESSAGE_TRAINRESULT = _descriptor.Descriptor(
  name='TrainResult',
  full_name='ParticipantMessage.TrainResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='theta', full_name='ParticipantMessage.TrainResult.theta', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=223,
)

_PARTICIPANTMESSAGE = _descriptor.Descriptor(
  name='ParticipantMessage',
  full_name='ParticipantMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='ParticipantMessage.result', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unkown_instruction', full_name='ParticipantMessage.unkown_instruction', index=1,
      number=1000, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_PARTICIPANTMESSAGE_TRAINRESULT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='request', full_name='ParticipantMessage.request',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=63,
  serialized_end=234,
)


_COORDINATORMESSAGE_TRAINCONFIG = _descriptor.Descriptor(
  name='TrainConfig',
  full_name='CoordinatorMessage.TrainConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='theta', full_name='CoordinatorMessage.TrainConfig.theta', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=340,
  serialized_end=396,
)

_COORDINATORMESSAGE = _descriptor.Descriptor(
  name='CoordinatorMessage',
  full_name='CoordinatorMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reconnect_in', full_name='CoordinatorMessage.reconnect_in', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='train_config', full_name='CoordinatorMessage.train_config', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_COORDINATORMESSAGE_TRAINCONFIG, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='instruction', full_name='CoordinatorMessage.instruction',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=237,
  serialized_end=411,
)

_PARTICIPANTMESSAGE_TRAINRESULT.fields_by_name['theta'].message_type = numproto_dot_protobuf_dot_ndarray__pb2._NDARRAY
_PARTICIPANTMESSAGE_TRAINRESULT.containing_type = _PARTICIPANTMESSAGE
_PARTICIPANTMESSAGE.fields_by_name['result'].message_type = _PARTICIPANTMESSAGE_TRAINRESULT
_PARTICIPANTMESSAGE.oneofs_by_name['request'].fields.append(
  _PARTICIPANTMESSAGE.fields_by_name['result'])
_PARTICIPANTMESSAGE.fields_by_name['result'].containing_oneof = _PARTICIPANTMESSAGE.oneofs_by_name['request']
_PARTICIPANTMESSAGE.oneofs_by_name['request'].fields.append(
  _PARTICIPANTMESSAGE.fields_by_name['unkown_instruction'])
_PARTICIPANTMESSAGE.fields_by_name['unkown_instruction'].containing_oneof = _PARTICIPANTMESSAGE.oneofs_by_name['request']
_COORDINATORMESSAGE_TRAINCONFIG.fields_by_name['theta'].message_type = numproto_dot_protobuf_dot_ndarray__pb2._NDARRAY
_COORDINATORMESSAGE_TRAINCONFIG.containing_type = _COORDINATORMESSAGE
_COORDINATORMESSAGE.fields_by_name['train_config'].message_type = _COORDINATORMESSAGE_TRAINCONFIG
_COORDINATORMESSAGE.oneofs_by_name['instruction'].fields.append(
  _COORDINATORMESSAGE.fields_by_name['reconnect_in'])
_COORDINATORMESSAGE.fields_by_name['reconnect_in'].containing_oneof = _COORDINATORMESSAGE.oneofs_by_name['instruction']
_COORDINATORMESSAGE.oneofs_by_name['instruction'].fields.append(
  _COORDINATORMESSAGE.fields_by_name['train_config'])
_COORDINATORMESSAGE.fields_by_name['train_config'].containing_oneof = _COORDINATORMESSAGE.oneofs_by_name['instruction']
DESCRIPTOR.message_types_by_name['ParticipantMessage'] = _PARTICIPANTMESSAGE
DESCRIPTOR.message_types_by_name['CoordinatorMessage'] = _COORDINATORMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ParticipantMessage = _reflection.GeneratedProtocolMessageType('ParticipantMessage', (_message.Message,), {

  'TrainResult' : _reflection.GeneratedProtocolMessageType('TrainResult', (_message.Message,), {
    'DESCRIPTOR' : _PARTICIPANTMESSAGE_TRAINRESULT,
    '__module__' : 'xain.network.stream_pb2'
    # @@protoc_insertion_point(class_scope:ParticipantMessage.TrainResult)
    })
  ,
  'DESCRIPTOR' : _PARTICIPANTMESSAGE,
  '__module__' : 'xain.network.stream_pb2'
  # @@protoc_insertion_point(class_scope:ParticipantMessage)
  })
_sym_db.RegisterMessage(ParticipantMessage)
_sym_db.RegisterMessage(ParticipantMessage.TrainResult)

CoordinatorMessage = _reflection.GeneratedProtocolMessageType('CoordinatorMessage', (_message.Message,), {

  'TrainConfig' : _reflection.GeneratedProtocolMessageType('TrainConfig', (_message.Message,), {
    'DESCRIPTOR' : _COORDINATORMESSAGE_TRAINCONFIG,
    '__module__' : 'xain.network.stream_pb2'
    # @@protoc_insertion_point(class_scope:CoordinatorMessage.TrainConfig)
    })
  ,
  'DESCRIPTOR' : _COORDINATORMESSAGE,
  '__module__' : 'xain.network.stream_pb2'
  # @@protoc_insertion_point(class_scope:CoordinatorMessage)
  })
_sym_db.RegisterMessage(CoordinatorMessage)
_sym_db.RegisterMessage(CoordinatorMessage.TrainConfig)



_PARTICIPANTMANAGER = _descriptor.ServiceDescriptor(
  name='ParticipantManager',
  full_name='ParticipantManager',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=413,
  serialized_end=492,
  methods=[
  _descriptor.MethodDescriptor(
    name='Connect',
    full_name='ParticipantManager.Connect',
    index=0,
    containing_service=None,
    input_type=_PARTICIPANTMESSAGE,
    output_type=_COORDINATORMESSAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PARTICIPANTMANAGER)

DESCRIPTOR.services_by_name['ParticipantManager'] = _PARTICIPANTMANAGER

# @@protoc_insertion_point(module_scope)
