# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xain/network/stream.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from numproto.protobuf import ndarray_pb2 as numproto_dot_protobuf_dot_ndarray__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='xain/network/stream.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x19xain/network/stream.proto\x1a\x1fnumproto/protobuf/ndarray.proto\"4\n\x12ParticipantMessage\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x10\n\x08progress\x18\x02 \x01(\x02\"\xce\x01\n\x12\x43oordinatorMessage\x12\x16\n\x0creconnect_in\x18\x02 \x01(\x05H\x00\x12\x37\n\x0ctrain_config\x18\x03 \x01(\x0b\x32\x1f.CoordinatorMessage.TrainConfigH\x00\x1a\\\n\x0bTrainConfig\x12)\n\x05theta\x18\x01 \x03(\x0b\x32\x1a.numproto.protobuf.NDArray\x12\x0e\n\x06\x65pochs\x18\x02 \x01(\x05\x12\x12\n\nepoch_base\x18\x03 \x01(\x05\x42\t\n\x07message2F\n\x0b\x43oordinator\x12\x37\n\x05Train\x12\x13.ParticipantMessage\x1a\x13.CoordinatorMessage\"\x00(\x01\x30\x01\x62\x06proto3')
  ,
  dependencies=[numproto_dot_protobuf_dot_ndarray__pb2.DESCRIPTOR,])




_PARTICIPANTMESSAGE = _descriptor.Descriptor(
  name='ParticipantMessage',
  full_name='ParticipantMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='ParticipantMessage.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='progress', full_name='ParticipantMessage.progress', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=114,
)


_COORDINATORMESSAGE_TRAINCONFIG = _descriptor.Descriptor(
  name='TrainConfig',
  full_name='CoordinatorMessage.TrainConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='theta', full_name='CoordinatorMessage.TrainConfig.theta', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='epochs', full_name='CoordinatorMessage.TrainConfig.epochs', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='epoch_base', full_name='CoordinatorMessage.TrainConfig.epoch_base', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=220,
  serialized_end=312,
)

_COORDINATORMESSAGE = _descriptor.Descriptor(
  name='CoordinatorMessage',
  full_name='CoordinatorMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reconnect_in', full_name='CoordinatorMessage.reconnect_in', index=0,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='train_config', full_name='CoordinatorMessage.train_config', index=1,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_COORDINATORMESSAGE_TRAINCONFIG, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='message', full_name='CoordinatorMessage.message',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=117,
  serialized_end=323,
)

_COORDINATORMESSAGE_TRAINCONFIG.fields_by_name['theta'].message_type = numproto_dot_protobuf_dot_ndarray__pb2._NDARRAY
_COORDINATORMESSAGE_TRAINCONFIG.containing_type = _COORDINATORMESSAGE
_COORDINATORMESSAGE.fields_by_name['train_config'].message_type = _COORDINATORMESSAGE_TRAINCONFIG
_COORDINATORMESSAGE.oneofs_by_name['message'].fields.append(
  _COORDINATORMESSAGE.fields_by_name['reconnect_in'])
_COORDINATORMESSAGE.fields_by_name['reconnect_in'].containing_oneof = _COORDINATORMESSAGE.oneofs_by_name['message']
_COORDINATORMESSAGE.oneofs_by_name['message'].fields.append(
  _COORDINATORMESSAGE.fields_by_name['train_config'])
_COORDINATORMESSAGE.fields_by_name['train_config'].containing_oneof = _COORDINATORMESSAGE.oneofs_by_name['message']
DESCRIPTOR.message_types_by_name['ParticipantMessage'] = _PARTICIPANTMESSAGE
DESCRIPTOR.message_types_by_name['CoordinatorMessage'] = _COORDINATORMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ParticipantMessage = _reflection.GeneratedProtocolMessageType('ParticipantMessage', (_message.Message,), {
  'DESCRIPTOR' : _PARTICIPANTMESSAGE,
  '__module__' : 'xain.network.stream_pb2'
  # @@protoc_insertion_point(class_scope:ParticipantMessage)
  })
_sym_db.RegisterMessage(ParticipantMessage)

CoordinatorMessage = _reflection.GeneratedProtocolMessageType('CoordinatorMessage', (_message.Message,), {

  'TrainConfig' : _reflection.GeneratedProtocolMessageType('TrainConfig', (_message.Message,), {
    'DESCRIPTOR' : _COORDINATORMESSAGE_TRAINCONFIG,
    '__module__' : 'xain.network.stream_pb2'
    # @@protoc_insertion_point(class_scope:CoordinatorMessage.TrainConfig)
    })
  ,
  'DESCRIPTOR' : _COORDINATORMESSAGE,
  '__module__' : 'xain.network.stream_pb2'
  # @@protoc_insertion_point(class_scope:CoordinatorMessage)
  })
_sym_db.RegisterMessage(CoordinatorMessage)
_sym_db.RegisterMessage(CoordinatorMessage.TrainConfig)



_COORDINATOR = _descriptor.ServiceDescriptor(
  name='Coordinator',
  full_name='Coordinator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=325,
  serialized_end=395,
  methods=[
  _descriptor.MethodDescriptor(
    name='Train',
    full_name='Coordinator.Train',
    index=0,
    containing_service=None,
    input_type=_PARTICIPANTMESSAGE,
    output_type=_COORDINATORMESSAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_COORDINATOR)

DESCRIPTOR.services_by_name['Coordinator'] = _COORDINATOR

# @@protoc_insertion_point(module_scope)
