# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xain/grpc/coordinator.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='xain/grpc/coordinator.proto',
  package='xain.protobuf.coordinator',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1bxain/grpc/coordinator.proto\x12\x19xain.protobuf.coordinator\x1a\x1bgoogle/protobuf/empty.proto\"R\n\x0fRendezvousReply\x12?\n\x08response\x18\x01 \x01(\x0e\x32-.xain.protobuf.coordinator.RendezvousResponse*+\n\x12RendezvousResponse\x12\n\n\x06\x41\x43\x43\x45PT\x10\x00\x12\t\n\x05LATER\x10\x01\x32\x61\n\x0b\x43oordinator\x12R\n\nRendezvous\x12\x16.google.protobuf.Empty\x1a*.xain.protobuf.coordinator.RendezvousReply\"\x00\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])

_RENDEZVOUSRESPONSE = _descriptor.EnumDescriptor(
  name='RendezvousResponse',
  full_name='xain.protobuf.coordinator.RendezvousResponse',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ACCEPT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LATER', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=171,
  serialized_end=214,
)
_sym_db.RegisterEnumDescriptor(_RENDEZVOUSRESPONSE)

RendezvousResponse = enum_type_wrapper.EnumTypeWrapper(_RENDEZVOUSRESPONSE)
ACCEPT = 0
LATER = 1



_RENDEZVOUSREPLY = _descriptor.Descriptor(
  name='RendezvousReply',
  full_name='xain.protobuf.coordinator.RendezvousReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='xain.protobuf.coordinator.RendezvousReply.response', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=169,
)

_RENDEZVOUSREPLY.fields_by_name['response'].enum_type = _RENDEZVOUSRESPONSE
DESCRIPTOR.message_types_by_name['RendezvousReply'] = _RENDEZVOUSREPLY
DESCRIPTOR.enum_types_by_name['RendezvousResponse'] = _RENDEZVOUSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RendezvousReply = _reflection.GeneratedProtocolMessageType('RendezvousReply', (_message.Message,), {
  'DESCRIPTOR' : _RENDEZVOUSREPLY,
  '__module__' : 'xain.grpc.coordinator_pb2'
  # @@protoc_insertion_point(class_scope:xain.protobuf.coordinator.RendezvousReply)
  })
_sym_db.RegisterMessage(RendezvousReply)



_COORDINATOR = _descriptor.ServiceDescriptor(
  name='Coordinator',
  full_name='xain.protobuf.coordinator.Coordinator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=216,
  serialized_end=313,
  methods=[
  _descriptor.MethodDescriptor(
    name='Rendezvous',
    full_name='xain.protobuf.coordinator.Coordinator.Rendezvous',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_RENDEZVOUSREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_COORDINATOR)

DESCRIPTOR.services_by_name['Coordinator'] = _COORDINATOR

# @@protoc_insertion_point(module_scope)
