# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from xain.grpc import hellonumproto_pb2 as xain_dot_grpc_dot_hellonumproto__pb2


class NumProtoServerStub(object):
  """package hellonumproto;

  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SayHelloNumProto = channel.unary_unary(
        '/NumProtoServer/SayHelloNumProto',
        request_serializer=xain_dot_grpc_dot_hellonumproto__pb2.NumProtoRequest.SerializeToString,
        response_deserializer=xain_dot_grpc_dot_hellonumproto__pb2.NumProtoReply.FromString,
        )


class NumProtoServerServicer(object):
  """package hellonumproto;

  """

  def SayHelloNumProto(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_NumProtoServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SayHelloNumProto': grpc.unary_unary_rpc_method_handler(
          servicer.SayHelloNumProto,
          request_deserializer=xain_dot_grpc_dot_hellonumproto__pb2.NumProtoRequest.FromString,
          response_serializer=xain_dot_grpc_dot_hellonumproto__pb2.NumProtoReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'NumProtoServer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
