# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from xain_fl.grpc import hellonumproto_pb2 as xain__fl_dot_grpc_dot_hellonumproto__pb2


class NumProtoServerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SayHelloNumProto = channel.unary_unary(
        '/hellonumproto.NumProtoServer/SayHelloNumProto',
        request_serializer=xain__fl_dot_grpc_dot_hellonumproto__pb2.NumProtoRequest.SerializeToString,
        response_deserializer=xain__fl_dot_grpc_dot_hellonumproto__pb2.NumProtoReply.FromString,
        )


class NumProtoServerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SayHelloNumProto(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_NumProtoServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SayHelloNumProto': grpc.unary_unary_rpc_method_handler(
          servicer.SayHelloNumProto,
          request_deserializer=xain__fl_dot_grpc_dot_hellonumproto__pb2.NumProtoRequest.FromString,
          response_serializer=xain__fl_dot_grpc_dot_hellonumproto__pb2.NumProtoReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'hellonumproto.NumProtoServer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
